### ISSUE TITLE
9.1.5 / 2.5.2 / 1.14.0 client crash / 使用字体导致无法启动游戏

### ISSUE THREAD

**Issue by fang2hou** [nowar-fonts/Nowar-Neo-Sans#1]
2021年9月3日, 暴雪上线了 9.1.5.39977 PTR 版本.
经过测试, 最新的 Release 版本字体无法正常使用, 启动游戏后会直接奔溃.

**Comment by fang2hou** [comment]
同样的情况貌似也出现在其他有爱字体上. (NGA有相关帖子, 但本人未验证)

**Comment by CyanoHao** [comment]
https://github.com/Stanzilla/WoWUIBugs/issues/164

It seems that they have misconfigured the freetype library.

I will try a TTF build.

**Comment by CyanoHao** [comment]
Here are TTF builds:

[NowarNeoSans-Bliz-300-0.8.0-TT.7z.zip](https://github.com/nowar-fonts/Nowar-Neo-Sans/files/7111780/NowarNeoSans-Bliz-300-0.8.0-TT.7z.zip)
[NowarNeoSans-Bliz-400-0.8.0-TT.7z.zip](https://github.com/nowar-fonts/Nowar-Neo-Sans/files/7111781/NowarNeoSans-Bliz-400-0.8.0-TT.7z.zip)
[NowarNeoSans-Bliz-500-0.8.0-TT.7z.zip](https://github.com/nowar-fonts/Nowar-Neo-Sans/files/7111782/NowarNeoSans-Bliz-500-0.8.0-TT.7z.zip)
[NowarNeoSans-Bliz-700-0.8.0-TT.7z.zip](https://github.com/nowar-fonts/Nowar-Neo-Sans/files/7111783/NowarNeoSans-Bliz-700-0.8.0-TT.7z.zip)

**Comment by CyanoHao** [comment]
The OTF issue has been fixed by Blizzard in 9.1.5.40078. It should be ported to 2.5.2 and 1.14.0 soon.
